target 'Plantasia' do
  use_frameworks!

  pod 'SnapKit', '~> 5.0.0'
  pod 'Bond', '~> 7.6.6'
  pod 'RealmSwift', '~> 4.4.1'
  pod 'DTPhotoViewerController', '~> 1.2.5'
  pod 'RAMAnimatedTabBarController', '~> 5.1.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
end

target 'Plantasia iMessageExtension' do
  use_frameworks!

  pod 'RealmSwift', '~> 4.4.1'
  pod 'Bond', '~> 7.6.6'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
end
