# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Plantasia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Plantasia
  pod 'SnapKit', '~> 5.0.0'
  pod 'Bond', '~> 7.6.6'
  pod 'RealmSwift', '~> 4.4.1'
  pod 'NVActivityIndicatorView', '~> 4.8.0'

end
